spring:
  application:
    name: spring-ai-alibaba-dynamic-mcp-server-example
  ai:
    mcp:
      server:
        name: dynamic-mcp-server
        version: 1.0.0

    alibaba:
      mcp:
        nacos:
          server-addr: localhost:8848
          namespace: eb466cbc-091a-4386-8b8d-6d1ce7b9d7c6
          username: nacos
          password: nacos
          dynamic:
            enabled: true
            service-names: webflux-mcp-server

server:
  port: 8092
