server:
  port: 8095

spring:
  application:
    name: mcp-nacos2-client-example
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications

    alibaba:
      mcp:
        nacos:
          enabled: true
          server-addr: 127.0.0.1:8848
          namespace: eb466cbc-091a-4386-8b8d-6d1ce7b9d7c6
          username: nacos
          password: nacos

        client:
          enabled: true
          sse:
            connections:
              server1:
                service-group:  mcp-server
                service-name: webflux-mcp-server
