server:
  port: 8090

spring:
  application:
    name: spring-ai-alibaba-helloworld

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

logging:
  level:
    # 设置Spring AI聊天客户端的Advisor日志级别
    org.springframework.ai.chat.client.advisor: DEBUG